baseURL = 'https://affirm-bats-yodel.github.io'
languageCode = 'ko-KR'
title = 'Lee Blog'
publishDir = 'docs'
theme = "hugo-bearblog"
author = 'Lee'

# Enable `robots.txt` for SEO
enableRobotsTXT = true

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = 'Lee Blog'
  dateFormat = "2006-01-02"
  [params.author]
    email = 'affirm-bats-yodel@duck.com'
    name = 'Lee'
